# Generated by Django 4.2.2 on 2023-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubladore',
            name='audio2',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='dubladore',
            name='audio3',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('JOVEM_FEMININA_PESADA', 'Jovem Feminina Pesada'), ('ADULTA_FEMININA_LEVE', 'Adulta Feminina Leve'), ('JOVEM_MASCULINA_LEVE', 'Jovem Masculina Leve'), ('IDOSA_MASCULINA_LEVE', 'Idosa Masculina Leve'), ('MEIA_IDADE_FEMININA', 'Meia Idade Feminina'), ('IDOSA_FEMININA_LEVE', 'Idosa Feminina Leve'), ('ADOLESCENTE_MASCULINA', 'Adolescente Masculina'), ('JOVEM_MASCULINA_PESADA', 'Jovem Masculina Pesada'), ('JOVEM_FEMININA_LEVE', 'Jovem Feminina Leve'), ('INFANTIL_MASCULINA', 'Infantil Masculina'), ('IDOSA_FEMININA', 'Idosa Feminina'), ('ADOLESCENTE_FEMININA', 'Adolescente Feminina'), ('INFANTIL_FEMININA', 'Infantil Feminina'), ('ADULTA_FEMININA_PESADA', 'Adulta Feminina Pesada'), ('IDOSA_FEMININA_PESADA', 'Idosa Feminina Pesada'), ('ADULTA_FEMININA', 'Adulta Feminina'), ('ADULTA_MASCULINA_LEVE', 'Adulta Masculina Leve'), ('ADULTA_MASCULINA', 'Adulta Masculina'), ('JOVEM_FEMININA', 'Jovem Feminina'), ('IDOSA_MASCULINA_PESADA', 'Idosa Masculina Pesada'), ('JOVEM_MASCULINA', 'Jovem Masculina'), ('ADULTA_MASCULINA_PESADA', 'Adulta Masculina Pesada'), ('MEIA_IDADE_MASCULINA', 'Meia Idade Masculina'), ('IDOSA_MASCULINA', 'Idosa Masculina')], max_length=2500),
        ),
    ]
