# Generated by Django 4.2.2 on 2023-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0004_alter_dubladore_canta_alter_dubladore_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='canta',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nâo')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Adulta Masculina', 'Adulta Masculina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Idosa Feminina', 'Idosa Feminina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Jovem Masculina', 'Jovem Masculina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Idosa Masculina', 'Idosa Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Jovem Feminina', 'Jovem Feminina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Infantil Masculina', 'Infantil Masculina')], max_length=2500),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='etnia',
            field=models.CharField(choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indigena', 'Indigena'), ('Parda', 'Parda'), ('Preta', 'Preta')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='orientacao',
            field=models.CharField(choices=[('Assexual', 'Assexual'), ('Bissexual', 'Bissexual'), ('Heterossexual', 'Heterossexual'), ('Homossexual', 'Homossexual'), ('Pansexual', 'Pansexual')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='pcd',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nâo')], default='Não', max_length=3),
        ),
    ]
