# Generated by Django 4.2.2 on 2023-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0005_alter_dubladore_canta_alter_dubladore_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Adulta Masculina', 'Adulta Masculina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Idosa Feminina', 'Idosa Feminina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Infantil Masculina', 'Infantil Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Idosa Masculina', 'Idosa Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Jovem Masculina', 'Jovem Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve')], max_length=2500),
        ),
    ]
