# Generated by Django 4.2.2 on 2023-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0006_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Idosa Masculina', 'Idosa Masculina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Jovem Masculina', 'Jovem Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Jovem Feminina', 'Jovem Feminina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Infantil Masculina', 'Infantil Masculina'), ('Idosa Feminina', 'Idosa Feminina'), ('Adulta Masculina', 'Adulta Masculina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada')], max_length=2500),
        ),
        migrations.CreateModel(
            name='FiltroHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.ManyToManyField(to='vox.dubladore')),
            ],
        ),
    ]