# Generated by Django 4.2.2 on 2023-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0007_caracteristica_alter_dubladore_categoria_filtrohome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Idosa Feminina', 'Idosa Feminina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Infantil Feminina', 'Infantil Feminina'), ('Idosa Masculina', 'Idosa Masculina'), ('Adulta Feminina', 'Adulta Feminina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Jovem Masculina', 'Jovem Masculina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Masculina', 'Adulta Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Jovem Feminina', 'Jovem Feminina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve')], max_length=2500),
        ),
    ]
