# Generated by Django 4.2.2 on 2023-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0008_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caracteristica',
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Jovem Feminina', 'Jovem Feminina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Idosa Feminina', 'Idosa Feminina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Idosa Masculina', 'Idosa Masculina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Adulta Feminina', 'Adulta Feminina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adulta Masculina', 'Adulta Masculina'), ('Infantil Feminina', 'Infantil Feminina'), ('Jovem Masculina', 'Jovem Masculina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada')], max_length=2500),
        ),
        migrations.DeleteModel(
            name='FiltroHome',
        ),
    ]