# Generated by Django 4.2.2 on 2023-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0010_dubladore_audio6_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubladore',
            name='audio4',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='dubladore',
            name='audio5',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Idosa Feminina', 'Idosa Feminina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Adulta Feminina', 'Adulta Feminina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Infantil Feminina', 'Infantil Feminina'), ('Jovem Feminina', 'Jovem Feminina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Idosa Masculina', 'Idosa Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Adulta Masculina', 'Adulta Masculina'), ('Jovem Masculina', 'Jovem Masculina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada')], max_length=2500),
        ),
    ]
