# Generated by Django 4.2.2 on 2023-06-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0011_dubladore_audio4_dubladore_audio5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Meia Idade Feminina', 'Meia Idade Feminina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adulta Masculina', 'Adulta Masculina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Infantil Feminina', 'Infantil Feminina'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Jovem Masculina', 'Jovem Masculina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Idosa Masculina', 'Idosa Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Idosa Feminina', 'Idosa Feminina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Jovem Feminina', 'Jovem Feminina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada')], max_length=2500),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='idiomas',
            field=models.CharField(max_length=60),
        ),
    ]
