# Generated by Django 4.2.2 on 2023-06-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0012_alter_dubladore_categoria_alter_dubladore_idiomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Jovem Masculina', 'Jovem Masculina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Adulta Masculina', 'Adulta Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Infantil Masculina', 'Infantil Masculina'), ('Infantil Feminina', 'Infantil Feminina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Idosa Masculina', 'Idosa Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Adulta Feminina', 'Adulta Feminina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Idosa Feminina', 'Idosa Feminina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve')], max_length=2500),
        ),
    ]
