# Generated by Django 4.2.2 on 2023-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0015_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Feminina', 'Jovem Feminina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Jovem Masculina', 'Jovem Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adulta Masculina', 'Adulta Masculina'), ('Idosa Masculina', 'Idosa Masculina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Infantil Feminina', 'Infantil Feminina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Idosa Feminina', 'Idosa Feminina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Infantil Masculina', 'Infantil Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Adulta Feminina', 'Adulta Feminina'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Idosa Feminina Leve', 'Idosa Feminina Leve')], max_length=2500),
        ),
    ]