# Generated by Django 4.2.2 on 2023-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0016_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Idosa Feminina', 'Idosa Feminina'), ('Idosa Masculina', 'Idosa Masculina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Jovem Masculina', 'Jovem Masculina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Adulta Masculina', 'Adulta Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Meia Idade Masculina', 'Meia Idade Masculina')], max_length=2500),
        ),
    ]
