# Generated by Django 4.2.2 on 2023-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0017_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Idosa Masculina', 'Idosa Masculina'), ('Infantil Masculina', 'Infantil Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Idosa Feminina', 'Idosa Feminina'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Masculina', 'Adulta Masculina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Infantil Feminina', 'Infantil Feminina'), ('Jovem Masculina', 'Jovem Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Adulta Feminina', 'Adulta Feminina')], max_length=2500),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='etnia',
            field=models.CharField(choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indigena', 'Indigena'), ('Parda', 'Parda'), ('Preta', 'Preta'), ('Não Informado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='foto_dublador'),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='genero',
            field=models.CharField(choices=[('Homem Cis', 'Homem Cis'), ('Homem Trans', 'Homem Trans'), ('intersexo', 'intersexo'), ('Mulher Cis', 'Mulher Cis'), (' Mulher Trans', ' Mulher Trans'), ('Não Binário', 'Não Binário'), ('Não Informado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='orientacao',
            field=models.CharField(choices=[('Assexual', 'Assexual'), ('Bissexual', 'Bissexual'), ('Heterossexual', 'Heterossexual'), ('Homossexual', 'Homossexual'), ('Pansexual', 'Pansexual'), ('Não Informado', 'Não Informado')], max_length=1000),
        ),
    ]
