# Generated by Django 4.2.2 on 2023-07-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0019_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(choices=[('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Adulta Feminina', 'Adulta Feminina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Infantil Feminina', 'Infantil Feminina'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Jovem Masculina', 'Jovem Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Adulta Masculina', 'Adulta Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Idosa Feminina', 'Idosa Feminina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Idosa Masculina', 'Idosa Masculina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada')], max_length=2500),
        ),
    ]
