# Generated by Django 4.2.2 on 2023-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0020_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='canta',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Nâo')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Infantil Masculina', 'Infantil Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Jovem Masculina', 'Jovem Masculina'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Idosa Masculina', 'Idosa Masculina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adulta Masculina', 'Adulta Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Infantil Feminina', 'Infantil Feminina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Adulta Feminina', 'Adulta Feminina'), ('Idosa Feminina', 'Idosa Feminina')], max_length=2500),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='dublador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indigena', 'Indigena'), ('Parda', 'Parda'), ('Preta', 'Preta'), ('Não Informado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='extensao_vocal',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='foto',
            field=models.ImageField(blank=True, default='default.png', upload_to='foto_dublador'),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='genero',
            field=models.CharField(blank=True, choices=[('Homem Cis', 'Homem Cis'), ('Homem Trans', 'Homem Trans'), ('intersexo', 'intersexo'), ('Mulher Cis', 'Mulher Cis'), (' Mulher Trans', ' Mulher Trans'), ('Não Binário', 'Não Binário'), ('Não Informado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='idiomas',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='nome_artistico',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='orientacao',
            field=models.CharField(blank=True, choices=[('Assexual', 'Assexual'), ('Bissexual', 'Bissexual'), ('Heterossexual', 'Heterossexual'), ('Homossexual', 'Homossexual'), ('Pansexual', 'Pansexual'), ('Não Informado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='pcd',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Nâo')], default='Não', max_length=3),
        ),
    ]