# Generated by Django 4.2.2 on 2023-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0022_alter_dubladore_categoria_alter_dubladore_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Idosa Feminina', 'Idosa Feminina'), ('Infantil Masculina', 'Infantil Masculina'), ('Jovem Masculina', 'Jovem Masculina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Adulta Masculina', 'Adulta Masculina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Idosa Masculina', 'Idosa Masculina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Jovem Feminina', 'Jovem Feminina'), ('Adulta Feminina', 'Adulta Feminina')], max_length=2500),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]