
# Generated by Django 4.2.2 on 2023-07-26 18:06

# Generated by Django 4.2.3 on 2023-07-25 17:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0023_alter_dubladore_categoria_alter_dubladore_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Jovem Feminina', 'Jovem Feminina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Infantil Masculina', 'Infantil Masculina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina', 'Jovem Masculina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Adulta Feminina', 'Adulta Feminina'), ('Idosa Feminina', 'Idosa Feminina'), ('Adulta Masculina', 'Adulta Masculina'), ('Idosa Masculina', 'Idosa Masculina')], max_length=2500),
        ),
    ]
