# Generated by Django 4.2.3 on 2023-07-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0026_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Idosa Feminina', 'Idosa Feminina'), ('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Infantil Masculina', 'Infantil Masculina'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Meia Idade Masculina', 'Meia Idade Masculina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Infantil Feminina', 'Infantil Feminina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Jovem Feminina', 'Jovem Feminina'), ('Jovem Masculina', 'Jovem Masculina'), ('Adulta Masculina', 'Adulta Masculina'), ('Idosa Masculina', 'Idosa Masculina'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Jovem Masculina Leve', 'Jovem Masculina Leve')], max_length=2500),
        ),
    ]
