# Generated by Django 4.2.3 on 2023-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0027_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Idosa Masculina Pesada', 'Idosa Masculina Pesada'), ('Adulta Feminina', 'Adulta Feminina'), ('Adulta Feminina Pesada', 'Adulta Feminina Pesada'), ('Infantil Feminina', 'Infantil Feminina'), ('Idosa Feminina', 'Idosa Feminina'), ('Meia Idade Feminina', 'Meia Idade Feminina'), ('Adulta Masculina Pesada', 'Adulta Masculina Pesada'), ('Idosa Feminina Pesada', 'Idosa Feminina Pesada'), ('Jovem Feminina', 'Jovem Feminina'), ('Adulta Masculina Leve', 'Adulta Masculina Leve'), ('Jovem Feminina Leve', 'Jovem Feminina Leve'), ('Jovem Masculina Pesada', 'Jovem Masculina Pesada'), ('Jovem Masculina Leve', 'Jovem Masculina Leve'), ('Infantil Masculina', 'Infantil Masculina'), ('Idosa Feminina Leve', 'Idosa Feminina Leve'), ('Adolescente Masculina', 'Adolescente Masculina'), ('Idosa Masculina Leve', 'Idosa Masculina Leve'), ('Adolescente Feminina', 'Adolescente Feminina'), ('Jovem Feminina Pesada', 'Jovem Feminina Pesada'), ('Idosa Masculina', 'Idosa Masculina'), ('Adulta Masculina', 'Adulta Masculina'), ('Adulta Feminina Leve', 'Adulta Feminina Leve'), ('Jovem Masculina', 'Jovem Masculina'), ('Meia Idade Masculina', 'Meia Idade Masculina')], max_length=2500),
        ),
    ]
