# Generated by Django 4.2.3 on 2023-07-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0029_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('InfantilFeminina', 'Infantil Feminina'), ('IdosaFeminina', 'Idosa Feminina'), ('IdosaMasculina', 'Idosa Masculina'), ('InfantilMasculina', 'Infantil Masculina'), ('AdultaFeminina', 'Adulta Feminina'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('AdultaMasculina', 'Adulta Masculina'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('JovemFemininaLeve', 'Jovem Feminina Leve'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('JovemMasculina', 'Jovem Masculina'), ('JovemFeminina', 'Jovem Feminina'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('AdolescenteFeminina', 'Adolescente Feminina')], max_length=2500),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Amarela', 'Amarela'), ('Branca', 'Branca'), ('Indigena', 'Indigena'), ('Parda', 'Parda'), ('Preta', 'Preta'), ('NaoInformado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='genero',
            field=models.CharField(blank=True, choices=[('HomemCis', 'Homem Cis'), ('HomemTrans', 'Homem Trans'), ('intersexo', 'intersexo'), ('MulherCis', 'Mulher Cis'), (' MulherTrans', ' Mulher Trans'), ('NaoBinario', 'Não Binário'), ('NaoInformado', 'Não Informado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='dubladore',
            name='orientacao',
            field=models.CharField(blank=True, choices=[('Assexual', 'Assexual'), ('Bissexual', 'Bissexual'), ('Heterossexual', 'Heterossexual'), ('Homossexual', 'Homossexual'), ('Pansexual', 'Pansexual'), ('NaoInformado', 'Não Informado')], max_length=1000),
        ),
    ]