# Generated by Django 4.2.3 on 2023-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0031_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('JovemMasculina', 'Jovem Masculina'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('JovemFemininaLeve', 'Jovem Feminina Leve'), ('AdultaMasculina', 'Adulta Masculina'), ('AdolescenteFeminina', 'Adolescente Feminina'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('InfantilFeminina', 'Infantil Feminina'), ('IdosaFeminina', 'Idosa Feminina'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('IdosaMasculina', 'Idosa Masculina'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('AdultaFeminina', 'Adulta Feminina'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('JovemFeminina', 'Jovem Feminina'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('InfantilMasculina', 'Infantil Masculina'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('AdultaFemininaLeve', 'Adulta Feminina Leve')], max_length=2500),
        ),
    ]
