# Generated by Django 4.2.3 on 2023-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0031_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('JovemFeminina', 'Jovem Feminina'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('AdolescenteFeminina', 'Adolescente Feminina'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('AdultaMasculina', 'Adulta Masculina'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('IdosaMasculina', 'Idosa Masculina'), ('JovemMasculina', 'Jovem Masculina'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('IdosaFeminina', 'Idosa Feminina'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('InfantilMasculina', 'Infantil Masculina'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('InfantilFeminina', 'Infantil Feminina'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('JovemFemininaLeve', 'Jovem Feminina Leve'), ('AdultaFeminina', 'Adulta Feminina'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada')], max_length=2500),
        ),
    ]
