# Generated by Django 4.2.3 on 2023-08-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0032_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('AdultaMasculina', 'Adulta Masculina'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('JovemMasculina', 'Jovem Masculina'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('InfantilMasculina', 'Infantil Masculina'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada'), ('IdosaMasculina', 'Idosa Masculina'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('IdosaFeminina', 'Idosa Feminina'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('AdolescenteFeminina', 'Adolescente Feminina'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('JovemFemininaLeve', 'Jovem Feminina Leve'), ('InfantilFeminina', 'Infantil Feminina'), ('JovemFeminina', 'Jovem Feminina'), ('AdultaFeminina', 'Adulta Feminina')], max_length=2500),
        ),
    ]
