# Generated by Django 4.2.3 on 2023-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0033_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('InfantilFeminina', 'Infantil Feminina'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('JovemFemininaLeve', 'Jovem Feminina Leve'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('IdosaFeminina', 'Idosa Feminina'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('InfantilMasculina', 'Infantil Masculina'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('AdultaMasculina', 'Adulta Masculina'), ('AdolescenteFeminina', 'Adolescente Feminina'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('IdosaMasculina', 'Idosa Masculina'), ('AdultaFeminina', 'Adulta Feminina'), ('JovemFeminina', 'Jovem Feminina'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('JovemMasculina', 'Jovem Masculina')], max_length=2500),
        ),
    ]
