# Generated by Django 4.2.3 on 2023-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0034_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('AdultaMasculina', 'Adulta Masculina'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('IdosaMasculina', 'Idosa Masculina'), ('AdolescenteFeminina', 'Adolescente Feminina'), ('InfantilFeminina', 'Infantil Feminina'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('IdosaFeminina', 'Idosa Feminina'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('InfantilMasculina', 'Infantil Masculina'), ('JovemFeminina', 'Jovem Feminina'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('JovemMasculina', 'Jovem Masculina'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('AdultaFeminina', 'Adulta Feminina'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('JovemFemininaLeve', 'Jovem Feminina Leve')], max_length=2500),
        ),
    ]
