# Generated by Django 4.2.3 on 2023-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0035_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('InfantilMasculina', 'Infantil Masculina'), ('JovemFemininaLeve', 'Jovem Feminina Leve'), ('JovemMasculina', 'Jovem Masculina'), ('IdosaMasculina', 'Idosa Masculina'), ('AdultaMasculina', 'Adulta Masculina'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('InfantilFeminina', 'Infantil Feminina'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('AdultaFeminina', 'Adulta Feminina'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('IdosaFeminina', 'Idosa Feminina'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('JovemFeminina', 'Jovem Feminina'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('AdolescenteFeminina', 'Adolescente Feminina')], max_length=2500),
        ),
    ]
