# Generated by Django 4.2.3 on 2023-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vox', '0036_alter_dubladore_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubladore',
            name='categoria',
            field=models.CharField(blank=True, choices=[('JovemFemininaLeve', 'Jovem Feminina Leve'), ('JovemMasculina', 'Jovem Masculina'), ('AdolescenteFeminina', 'Adolescente Feminina'), ('MeiaIdadeFeminina', 'Meia Idade Feminina'), ('IdosaMasculinaLeve', 'Idosa Masculina Leve'), ('JovemFemininaPesada', 'Jovem Feminina Pesada'), ('InfantilFeminina', 'Infantil Feminina'), ('IdosaMasculina', 'Idosa Masculina'), ('AdultaMasculinaLeve', 'Adulta Masculina Leve'), ('IdosaFeminina', 'Idosa Feminina'), ('JovemFeminina', 'Jovem Feminina'), ('IdosaMasculinaPesada', 'Idosa Masculina Pesada'), ('AdultaFemininaLeve', 'Adulta Feminina Leve'), ('AdolescenteMasculina', 'Adolescente Masculina'), ('MeiaIdadeMasculina', 'Meia Idade Masculina'), ('AdultaFemininaPesada', 'Adulta Feminina Pesada'), ('AdultaFeminina', 'Adulta Feminina'), ('IdosaFemininaPesada', 'Idosa Feminina Pesada'), ('IdosaFemininaLeve', 'Idosa Feminina Leve'), ('InfantilMasculina', 'Infantil Masculina'), ('JovemMasculinaLeve', 'Jovem Masculina Leve'), ('AdultaMasculina', 'Adulta Masculina'), ('AdultaMasculinaPesada', 'Adulta Masculina Pesada'), ('JovemMasculinaPesada', 'Jovem Masculina Pesada')], max_length=2500),
        ),
    ]
